// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX4LnrMZJJ_Q5LsHkBR8fv7t5caI4Gck4',
    appId: '1:945163606588:web:335f7069899aaee51f4139',
    messagingSenderId: '945163606588',
    projectId: 'fitworkoutplanner',
    authDomain: 'fitworkoutplanner.firebaseapp.com',
    storageBucket: 'fitworkoutplanner.appspot.com',
    measurementId: 'G-62CJ2M46LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSIzrm8o0zVOAtQ8_O8UzpxrGVIZp7nAg',
    appId: '1:945163606588:android:2b46fc7033a5f49f1f4139',
    messagingSenderId: '945163606588',
    projectId: 'fitworkoutplanner',
    storageBucket: 'fitworkoutplanner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMor55JBQb7ipIGUQWGcGljR3Z9Rgs17E',
    appId: '1:945163606588:ios:f0da7a3fac79fba01f4139',
    messagingSenderId: '945163606588',
    projectId: 'fitworkoutplanner',
    storageBucket: 'fitworkoutplanner.appspot.com',
    iosClientId: '945163606588-em8o3o93j9oeoato6rbap8sqn6ppmbg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMor55JBQb7ipIGUQWGcGljR3Z9Rgs17E',
    appId: '1:945163606588:ios:f0da7a3fac79fba01f4139',
    messagingSenderId: '945163606588',
    projectId: 'fitworkoutplanner',
    storageBucket: 'fitworkoutplanner.appspot.com',
    iosClientId: '945163606588-em8o3o93j9oeoato6rbap8sqn6ppmbg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.workoutPlanner',
  );
}
